django_web_app/Projecteam/urls.py
from django.urls import path

from .views import TeamCreate,TeamList,teamDetail,Filedelete,Fileupload,search,memeberTeam,delTeam

app_name = 'team'
urlpatterns = [
path('create/',TeamCreate,name="add"),
path('',TeamList,name="list"),
path('myteam/',memeberTeam,name="mlist"),
path('detial/<str:name>',teamDetail,name="detail"),
path('delf/<str:name>',Filedelete,name="del"),
path('upload/<str:name>',Fileupload,name='upload'),
path('search/',search,name="search"),
path('del/<int:id>',delTeam,name="teamdel"),

]

django_web_app/blog/urls.py
from django.urls import path,include
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    AddComments,
  about,gitDetails,gitsearch
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('media/Files/<int:pk>',PostDeleteView.as_view(),name='post-delete' ),
    path('search/',views.search,name='search' ),
    path('gse/',gitsearch,name="gs"),
    path('comment/<int:pk>',AddComments,name='comments'),
    path('about/',about,name="about"),
    path('det/<str:id>',gitDetails,name="gitdetails")
]

django_web_app/django_web_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_views.Login, name='login'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
path('comment/', include('comment.urls')),
    path('team/',include('Projecteam.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_web_app/Projecteam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django_web_app import settings
import os
import shutil
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment

def nameing(self,filename):
    path = "TeamFiles"
    if os.path.exists(os.path.join(settings.MEDIA_ROOT, path, self.user.name)):
        return path + "/" + self.user.name+"/"+filename
    else:
        os.makedirs(os.path.join(settings.MEDIA_ROOT, path, self.user.name))
        return path + "/" + self.user.name+"/"+filename

class projectdb(models.Model):
    name=models.CharField(max_length=30,unique=True)
    title=models.CharField(max_length=20)
    leader=models.ForeignKey(User,on_delete=models.CASCADE)
    member=ArrayField(models.CharField(max_length=255),size=4)
    status=models.BooleanField(default=False)
    comments = GenericRelation(Comment)



    def __str__(self):
        return "{} - {}".format(self.name,self.title)

    def delete(self, *args, **kwargs):
        path = "TeamFiles"
        if os.path.isdir(os.path.join(settings.MEDIA_ROOT, path, self.name)):
            shutil.rmtree(os.path.join(settings.MEDIA_ROOT, path, self.name))
        super().delete(*args, **kwargs)  # Call the "real" save() method.

class projectFiles(models.Model):
    user=models.ForeignKey(projectdb,on_delete=models.CASCADE)
    file=models.FileField(upload_to=nameing)

    def delete(self, *args, **kwargs):
        path = "TeamFiles"
        os.remove(settings.MEDIA_ROOT+'/'+str(self.file))
        super().delete(*args,**kwargs)

    def __str__(self):
        return "{} ".format(self.user.name)

django_web_app/Projecteam/forms.py
from django import forms
from django.forms import ClearableFileInput
from django.contrib.auth.models import User

class TeamCreations(forms.Form):
    name=forms.CharField(max_length=30)
    title=forms.CharField(max_length=20)
    # file=forms.FileField(required=False,widget=ClearableFileInput(attrs={'multiple': True}))
    status=forms.BooleanField(required=False)

django_web_app/Projecteam/views.py
import os
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .models import projectdb,projectFiles
from django.db.models import Q
from .forms import TeamCreations


def TeamCreate(request):
    if request.method =="POST":
        form=TeamCreations(request.POST)
        print('entered')
        if form.is_valid():
            print(form.cleaned_data['status'],"***************")
            db=projectdb(name=form.cleaned_data['name'],
                      title=form.cleaned_data['title'],
                      leader=request.user,
                    status=form.cleaned_data['status'],
                      member=request.POST.getlist('members'))
            db.save()
            recp=[request.user.email]
            for i in db.member:
                recp.append(User.objects.filter(username__icontains=i).first().email)

            send_mail(
                'team created',
                'you  have been selected to  {} project under the leadership of {}'.format(db.title,request.user),
                None,
                recp,
                fail_silently=True, )
            return redirect("team:list")
    form=TeamCreations()
    choose = []
    res = User.objects.all()
    for i in res:
        choose.append((str(i.username), str(i.username)))
    context={'list':choose,'form':form}
    return render(request,"Projecteam/project.html",context)

def TeamList(request):
    projects=projectdb.objects.filter(status=True)
    print(projects,"*************")
    alist = []
    for i in range(0, len(projects) - 1, 2):
        alist.append([projects[i], projects[i + 1]])
    if len(projects) % 2 != 0:
        alist.append([projects[len(projects) - 1], None])
    paginator = Paginator(alist, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    res = page_obj.paginator.count
    context = {"page_obj": page_obj}
    return render(request,"Projecteam/teamlist.html",context)

def teamDetail(request,name):
    details=projectdb.objects.filter(name=name).first()
    Files=projectFiles.objects.filter(user=details)
    filename=[]
    if str(request.user)==str(details.leader.username):
        lead,mem=True,True
    elif str(request.user) in details.member:
        lead,mem=False,True
    else:
        lead,mem=False,False
    for i in Files:
        filename.append(str(os.path.basename(str(i.file))).strip(" "))
    Files=list(zip(filename,Files))
    members=""
    for i in range(len(details.member)-1):
        members+=details.member[i]+" ,"
    members+=" "+details.member[len(details.member)-1]
    context={"details":details,"files":Files,"lead":lead,"mem":mem,'members':members}
    return render(request,"Projecteam/details.html",context)


def Filedelete(request,name):
    user=projectdb.objects.filter(name=name).first()
    res=projectFiles.objects.filter(file__icontains=name,user=user).first()
    if res:
        res.delete()
    return redirect('team:detail',name=user.name)

def Fileupload(request,name):
    user = projectdb.objects.filter(name=name).first()
    t=projectFiles(user=user,file=request.FILES.get('file'))
    t.save()
    return redirect("team:detail",name=user.name)

def search(request):
    obj=str(request.GET.get('q'))
    projects = projectdb.objects.filter(Q(name=obj) |
                                     Q(title=obj) | Q(leader=User.objects.filter(username=obj).first()) |
                                     Q(member__contains=[obj]))
    alist = []
    for i in range(0, len(projects) - 1, 2):
        alist.append([projects[i], projects[i + 1]])
    if len(projects) % 2 != 0:
        alist.append([projects[len(projects) - 1], None])
    paginator = Paginator(alist, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj,'qu':True,'q':obj}
    return render(request, "Projecteam/teamlist.html", context)

def memeberTeam(request):
    projects = projectdb.objects.filter(Q(leader=request.user)|Q(member__contains=[request.user]))
    alist = []
    for i in range(0, len(projects) - 1, 2):
        alist.append([projects[i], projects[i + 1]])
    if len(projects) % 2 != 0:
        alist.append([projects[len(projects) - 1], None])
    paginator = Paginator(alist, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "Projecteam/myTeamlist.html", context)

def delTeam(request,id):
    res=projectdb.objects.filter(id=id).first()
    recp=[]
    for i in res.member:
        recp.append(User.objects.filter(username__icontains=i).first().email)
    send_mail(
        'Team Terminated',
        'team has been deleted by leader {}'.format(request.user),
        None,
        recp,
        fail_silently=True, )
    res.delete()
    return redirect("team:mlist")

django_web_app/Projecteam/templates/Projecteam/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Project Portal</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> Project Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>



                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'team:search' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>

                    {% if user.is_authenticated %}

                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'team:mlist'  %}" class="btn text-white m-2"><i class="fas fa-users"></i> My Team</a>
                    <a href="{% url 'team:list' %}" class="btn text-white m-2"><i class="fas fa-project-diagram"></i> Project </a>
                    <a href="{% url 'team:add' %}" class="btn text-white m-2"><i class="fas fa-user-plus"></i> New Team </a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    {% endif %}

                </div>
              </nav>
      <div class="container my-bg">
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
{% block content %}
 {% endblock %}

django_web_app/Projecteam/templates/Projecteam/base2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

      <script>
  $(document).ready(function() {
    $('#idOfFirstSelect').focus();
   $('.user').select2({
     placeholder:"select memeber....",
      maximumSelectionLength: 5,
allowClear: true
   });
});
  </script>
    <title>Project Portal</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> Project Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>



                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'team:search' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>

                    {% if user.is_authenticated %}

                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'team:mlist'  %}" class="btn text-white m-2"><i class="fas fa-users"></i> My Team</a>
                    <a href="{% url 'team:list' %}" class="btn text-white m-2"><i class="fas fa-project-diagram"></i> Project </a>
                    <a href="{% url 'team:add' %}" class="btn text-white m-2"><i class="fas fa-user-plus"></i> New Team </a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    {% endif %}

                </div>
              </nav>
      <div class="container my-bg">
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
{% block content %}
 {% endblock %}

django_web_app/Projecteam/templates/Projecteam/createTeam.html
{% extends "Projecteam/base2.html" %}
{% block content %}
<center>

        <form method="POST"  > {% csrf_token %}
        {{ form.as_p }}
      <select class="user" id="idOfFirstSelect" name="members" multiple style="width: 30%">
        {% for i,j in list %}
        <option value={{i}}>{{j}}</option>-->
        {% endfor %}
      </select>
            <br>
        <input type="submit">
    </div>
          <!-- Default disabled -->


        </form>

    </center>
{% endblock %}

django_web_app/Projecteam/templates/Projecteam/details.html
{% extends "Projecteam/base.html" %}
{% block content %}
<style>
    .newsletter-subscribe{color:#313437;background-color:#fff;padding:50px 0}
.newsletter-subscribe h2{font-size:24px;font-weight:700;margin-bottom:25px;line-height:1.5;padding-top:0;margin-top:0;color:inherit}
</style>

<div class="newsletter-subscribe">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro">
                <h1 class="text-center">{{ details.name }}</h1>
                <h1 class="text-center">{{ details.title }}</h1>
                <h4 class="text-center"><i class="fa fa-user"></i> {{ details.leader }}</h4>
                <h4 class="text-center"><i class="fas fa-users"></i> {{ members }}</h4>
            </div>
            <!-- End: Intro -->

        </div>
    </div>


<center>
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Files
  </div>
  <ul class="list-group list-group-flush">
      {% for i,j in files %}

      {% if j.file %}
    <li class="list-group-item" >
        <a href="{{ j.file.url }}" > {{ i }} </a>
    {% if lead %}
      <a href="{% url 'team:del' details.name  %}" class="btn btn-danger" style="height:30px;margin-left:50px;padding-top:2px;">delete</a>
      {% endif %}
    </li>

      {% endif %}

  {% endfor %}
  </ul>
</div>
    {% if mem %}
    <p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    upload
  </button>
</p>
    {% endif %}
    </center>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
<form    action="{% url 'team:upload'  details.name %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
                    <input id="id_file" name="file" type="file"  placeholder="Search Here..." />
    <input type="submit" class="btn btn-warning"/>
</form>

  </div>
</div>
{% load comment_tags %}  {# Loading the template tag #}

{% render_comments details request %}  {# Include comments belonging to a certain object #}
{% include_static %}
{% endblock %}

django_web_app/Projecteam/templates/Projecteam/myTeamlist.html
{% extends "Projecteam/base.html" %}
{% block content %}
{% for i,j in page_obj %}
    <div class="card-group" style="padding: 0px;">

        <div class="card" style="margin: 8px;">
            <div class="card-body">
                <p class="card-text" style="font-size: 40px;"><strong><em>{{ i.name }} / {{ i.title }}</em></strong>&nbsp;</p>
<!--                <p style="font-size: 23px;"><strong>Our team {{ i.name }}</strong></p>-->
                <p><i class="fa fa-user"></i>&nbsp;{{ i.leader }}</p>
                <button class="btn btn-primary"  type="button" onclick="location.href='{% url 'team:detail' i.name %}'">View</button>
                {% if request.user.username == i.leader.username %}
                <button class="btn btn-danger"  type="button" onclick="location.href='{% url 'team:teamdel' i.id %}'">Delete</button>
                 {% endif %}
            </div>
        </div>
        {% if j %}
           <div class="card" style="margin: 8px;">
            <div class="card-body">
                <p class="card-text" style="font-size: 40px;"><strong><em>{{ j.name }} / {{ j.title }}</em></strong>&nbsp;</p>
<!--                <p style="font-size: 23px;"><strong>Our team {{ j.name }}</strong></p>-->
                <p><i class="fa fa-user"></i>&nbsp;{{ j.leader }}</p>
                <button class="btn btn-primary"  type="button" onclick="location.href='{% url 'team:detail' j.name %}'">View</button>
                {% if request.user.username == j.leader.username %}
                <button class="btn btn-danger" type="button" onclick="location.href='{% url 'team:teamdel' j.id %}'">Delete</button>
                 {% endif %}
            </div>
       </div>
       {% endif %}


    </div>
    {% endfor %}

{% if page_obj %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}

django_web_app/Projecteam/templates/Projecteam/project.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'Projecteam/team2.css' %}">

      <script>
  $(document).ready(function() {
    $('#idOfFirstSelect').focus();
   $('.user').select2({
     placeholder:"select memeber....",
      maximumSelectionLength: 5,
allowClear: true
   });
});
  </script>
    <title>Project Portal</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> Project Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>



                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'team:search' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>

                 

                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'team:mlist'  %}" class="btn text-white m-2"><i class="fas fa-users"></i> My Team</a>
                    <a href="{% url 'team:list' %}" class="btn text-white m-2"><i class="fas fa-project-diagram"></i> Project </a>
                    <a href="{% url 'team:add' %}" class="btn text-white m-2"><i class="fas fa-user-plus"></i> New Team </a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    

                </div>
              </nav>
<center>
<div class="team-box">
        <form method="POST"  > {% csrf_token %}
        <h1>Create Team</h1>
        <input type="text" name="title" placeholder="Title">
        <input type="text" name="name" placeholder="Team Name">
      <select class="user" id="idOfFirstSelect" name="members" multiple style="width: 100%">
        {% for i,j in list %}
        <option value={{i}}>{{j}}</option>-->
        {% endfor %}
      </select>
            <div>
                <label for="check">public <input type="checkbox" id="check" name="status" ></label>
                 </div>
        <input type="submit">
    </div>
          <!-- Default disabled -->
</form>
</div>

    </center>
      

</body>
</html>