django_web_app/Projecteam/urls.py
from django.urls import path

from .views import TeamCreate,TeamList,teamDetail,Filedelete,Fileupload,search,memeberTeam,delTeam

app_name = 'team'
urlpatterns = [
path('create/',TeamCreate,name="add"),
path('',TeamList,name="list"),
path('myteam/',memeberTeam,name="mlist"),
path('detial/<str:name>',teamDetail,name="detail"),
path('delf/<str:name>',Filedelete,name="del"),
path('upload/<str:name>',Fileupload,name='upload'),
path('search/',search,name="search"),
path('del/<int:id>',delTeam,name="teamdel"),

]

django_web_app/blog/urls.py
from django.urls import path,include
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    AddComments,
  about,gitDetails,gitsearch
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('media/Files/<int:pk>',PostDeleteView.as_view(),name='post-delete' ),
    path('search/',views.search,name='search' ),
    path('gse/',gitsearch,name="gs"),
    path('comment/<int:pk>',AddComments,name='comments'),
    path('about/',about,name="about"),
    path('det/<str:id>',gitDetails,name="gitdetails")
]

django_web_app/django_web_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_views.Login, name='login'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
path('comment/', include('comment.urls')),
    path('team/',include('Projecteam.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_web_app/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from users.models import Profile
import os

class Post(models.Model):
	title = models.CharField(max_length=100)
	file = models.FileField(null=True,blank=True,upload_to='Files')
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def extension(self):
		name, extension = os.path.splitext(self.file.name)
		return extension

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

	def delete(self, *args, **kwargs):
		if os.path.isfile(self.file.path):
			os.remove(self.file.path)
		super(Post, self).delete(*args, **kwargs)


class Comments(models.Model):
	usr=models.ForeignKey(User,on_delete=models.CASCADE)
	post=models.ForeignKey(Post,related_name="comments",on_delete=models.CASCADE)
	com=models.TextField()
	time=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "{} - {}".format(self.usr,self.post)

	class Meta:
		ordering=['-time']


class gitrep(models.Model):
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	respo = models.CharField(max_length=255)
	files = models.CharField(max_length=255)
	download = models.CharField(max_length=255)
	time = models.DateField(auto_now=False, auto_now_add=False)
	rpid=models.CharField(max_length=255)

	class Meta:
		ordering = ['-time']
	def __str__(self):
		return '{} - {}'.format(self.respo,self.profile.user.username)

django_web_app/blog/views.py
import requests
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404,redirect
from .models import Comments
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post,gitrep
from users.models import Profile
from django.urls import reverse_lazy
from django.contrib.staticfiles.views import serve

from django.db.models import Q


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

def search(request):
    template='blog/home.html'

    query=request.GET.get('q')

    result=Post.objects.filter(Q(title__icontains=query) | Q(author__username__icontains=query) | Q(content__icontains=query))
    paginate_by=6
    context={ 'posts':result }
    return render(request,template,context)

def gitsearch(request):
    query = request.GET.get('q')
    projects=gitrep.objects.filter(Q(respo__icontains=query) | Q(profile__user__username__icontains=query))
    alist = []
    for i in range(0, len(projects) - 1, 2):
        alist.append([projects[i], projects[i + 1]])
    if len(projects) % 2 != 0:
        alist.append([projects[len(projects) - 1], None])
    paginator = Paginator(alist, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    res = page_obj.paginator.count
    context = {"page_obj": page_obj,'qu':True,'q':query}
    return render(request, 'blog/about.html', context)
   


def getfile(request):
   return serve(request, 'File')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    # context_object_name = 'posts'
    paginate_by = 6

    # def get_queryset(self):
    #     user = get_object_or_404(User, username=self.kwargs.get('username'))
    #     return Post.objects.filter(author=user).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        context['posts']=Post.objects.filter(author=user).order_by('-date_posted')
        u=Profile.objects.filter(user=user).first()
        context['git']=gitrep.objects.filter(profile=u)
        context['author']=user.username
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    # queryset = Comments.objects.filter(post=Post.objects.filter(id=DetailView.request.get['pk']))


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = 'blog/post_confirm_delete.html'


    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False




def AddComments(request,pk):
    if  request.GET['com']:
        postc=Post.objects.filter(id=pk)
        c=Comments(usr=request.user,post=postc[0],com=request.GET['com'])
        c.save()
    return redirect('post-detail', pk=pk)

def about(request):
    projects=gitrep.objects.all()
    alist = []
    for i in range(0, len(projects) - 1, 2):
        alist.append([projects[i], projects[i + 1]])
    if len(projects) % 2 != 0:
        alist.append([projects[len(projects) - 1], None])
    paginator = Paginator(alist, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    res = page_obj.paginator.count
    context = {"page_obj": page_obj}
    return render(request, 'blog/about.html', context)

def gitDetails(request,id):
    detail=gitrep.objects.filter(rpid=id).first()
    yet=requests.get(detail.files)
    det=yet.json()
    for i in det['tree']:
        print(i)
    context={'del':det['tree'],'det':detail}
    return render(request,'blog/list.html',context)

django_web_app/blog/templates/blog/about.html
{% extends "blog/gbase.html" %}
{% block content %}
{% for i,j in page_obj %}
    <div class="card-group" style="padding: 0px;">

        <div class="card" style="margin: 8px;">
            <div class="card-body">

                <p class="card-text" style="font-size: 40px;"><strong><em>{{ i.respo }}</em></strong>&nbsp;</p>
                <p style="font-size: 23px;"><strong>Team {{ i.profile.user.username }}</strong></p>
                <button class="btn btn-primary"  type="button" onclick="location.href='{% url 'gitdetails' i.rpid %}'">View</button>

                </div>
                </div>

        {% if j %}
           <div class="card" style="margin: 8px;">
            <div class="card-body">

                <p class="card-text" style="font-size: 40px;"><strong><em>{{ j.respo }}</em></strong>&nbsp;</p>
                <p style="font-size: 23px;"><strong>Team {{ j.profile.user.username }}</strong></p>
                <button class="btn btn-primary"  type="button" onclick="location.href='{% url 'gitdetails' j.rpid %}'">View</button>


                </div>
       </div>
       {% endif %}


    </div>
    {% endfor %}
{% if qu %}
{% if page_obj %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?q={{ q }}&page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?q={{ q }}&page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?q={{ q }}&page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?q={{ q }}&page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?q={{ q }}&page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?q={{ q }}&page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% else %}
{% if page_obj %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endif %}
{% endblock %}

django_web_app/blog/templates/blog/base.html
{% load static %}
<html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'blog/css/style1.css' %}">
        <title>Project Portal</title>
 {% block add %}
      {% endblock %}
</head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> Project Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                      {% if user.is_authenticated %}
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>
                      {% else %}
                      <li class="nav-item active">
                      <a href="{% url 'about'  %}" class="btn text-white m-2"><i class="fab fa-github"></i> Github</a>
                    </li>
                      {% endif %}
                   

                    
                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'search' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>
              
                    {% if user.is_authenticated %}
                    <a href="{% url 'about'  %}" class="btn text-white m-2"><i class="fab fa-github"></i> Github</a>
                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'team:list' %}" class="btn text-white m-2"><i class="fas fa-users"></i> Team </a>
                    <a href="{% url 'team:add' %}" class="btn text-white m-2"><i class="fas fa-user-plus"></i> New Team </a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    
                    {% else %}
                    <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>
                   
                    <a href="{% url 'register' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
                    {% endif %}
                  
                </div>
              </nav>
      <div class="container my-bg">
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
    {% block content %}
      
    {% endblock  %}
</div> 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'blog/css/main.js' %}"></script>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

django_web_app/blog/templates/blog/gbase.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Project Portal</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> Project Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>



                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'gs' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>

                    {% if user.is_authenticated %}

                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'team:mlist'  %}" class="btn text-white m-2"><i class="fas fa-users"></i> My Team</a>
                    <a href="{% url 'team:list' %}" class="btn text-white m-2"><i class="fas fa-project-diagram"></i> Project </a>
                    <a href="{% url 'team:add' %}" class="btn text-white m-2"><i class="fas fa-user-plus"></i> New Team </a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    {% endif %}

                </div>
              </nav>
      <div class="container my-bg">
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
{% block content %}
 {% endblock %}

django_web_app/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
      <div class="jumbotron mt-3 bg-white shadow-lg">
      <article class="media content-section shadow">
        <a href="{{ post.author.profile.image.url }} " target="_blank"> <img src="{{ post.author.profile.image.url }}  " alt="" class="article-img rounded-circle img-thumbnail img-fluid shadow">
        </a>
        <div class="media-body">
          <div class="article-metadata d-flex justify-content-between">
            <a class="mr-2 " href="{% url 'user-posts' post.author.username  %}"><h3>{{ post.author }}</h3></a>
              <small class="text-muted">{{ post.date_upload|date:"F d, Y" }}</small>
          </div>
          {% if post.file %}
          <a href="{{ post.file.url }}"  download class="text-dark text-justify "><h5>{{ post.blog }}</h5></a>
          {% endif %}
     
      
     
          <h2><a class="article-title text-justify " href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
          <div class="d-flex justify-content-between">
            <p class="article-content text-justify text-truncate overflow-hidden">{{ post.content }}</p>
            {% if post.file %}
          <div class="form-group mt-0 pt-0  m-2">          
            <a class="btn btn-outline-primary  btn-d "  href="{{ post.file.url }}"  download type="submit"><i class="fas fa-download"></i></a>
          </div>
          {% endif %}
        
          </div>
        </div>
      </article>
      </div>

    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

django_web_app/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

django_web_app/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section pt-2 mt-3 shadow-lg"  >
          <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Post
                    </legend>
                    {{ form|crispy }}
              </fieldset>
              <div class="form-group">
                  
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-upload"></i> Upload</button>
              </div>
          </form>
         
      </div>
{% endblock content %}

django_web_app/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-4" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>

    {% endfor %}
{% for post in git %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-4" href="#">{{ author }}</a>
              <small class="text-muted">{{ post.time|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'gitdetails' post.rpid %}">{{ post.profile.github }}/{{ post.respo }}</a></h2>
          </div>
        </article>

    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}